### PR TITLE
Update for HumHub 1.14

### LINKED ISSUE #1: Не работает на HumHub 1.13.2.
Не работает на HumHub 1.13.2.
Ошибка: Undefined variable $submitUrl.

### PR DESCRIPTION
**Pull request by felixhahnweilheim**
Hi, I've tested this theme with HumHub v1.14.0-beta2 and got a lot of errors because of outdated view files.
I have updated most of them but also removed one because I didn't see a reason why it was there.
Probably the changes also work for HumHub 1.13 but I didn't test it.

Unfortunately the code is not well documented, so you have to guess and compare what the developer(s) wanted to achieve.

One issue that still has to be solved:

- [x] uploading file in comment (button disappears when clicked)
This doesn't seem to be a view file problem but a css issue. It would be the simplest solution to remove all the customization of the post and comment create forms. Since HumHub v1.12 or 1.13 the default forms should be good enough.
@WebCrew , what do you think?

Apart from that I have shortly(!) tested the most important things like creating posts and comments.

This PR fixes https://github.com/WebCrew/HumHub_Flathub_Updated/issues/1

### CODE REVIEW

**Comment by felixhahnweilheim** [comment]
I have now (very shortly) tested with HumHub 1.13, it seems to work.

Fixed editing of posts and comments.

I would suggest to start a versioning. So create a tag (e.g. "v2.0") with the current state before merging this PR and then call it v2.1.

Apart from the remaining issue (file upload in comments) my PR is ready to merge.

**Comment by WebCrew** [comment]
Wow Felix, great job man! Because I am not familar with all the Git features like creating tags with 2.0 etc. I invited you to the repo as a contributor. **I give you a free hand with the repository**. You did a great job man.

Apart from that, I'm pretty much out of the HumHub topic. I don't have a clue about it anymore, nor have I set up an up-to-date installation. So unfortunately I'm not really of any help, **but I'm still very pleased that you are breathing new life into Felix's beautiful theme**.

Du bist wie ich aus Bayern lol - ich komme ursprünglich aus Holzkirchen, lebte später in München Riem und jetzt bin ich in Stuttgart.

Sorry aber wie gesagt ich kenn mich mit all den GitHub Funktionen nicht besonders aus, ich hoffe es ist ausreichend wenn ich Dich als Contributor dem Repo hinzufüge? Dann könntest Du alles selbst so managen wie Du es für richtig hältst. Wenn Du möchtest gib ich das Repo auch komplett an Dich ab?

Grüße, Andi

**Comment by felixhahnweilheim** [comment]
Thanks, I have created a v2.0 tag and then merged this PR. As soon as the missing issue is solved I would create a v2.1 tag.

Das ist aber ein Zufall, mein Vater kommt aus Holzkirchen und meine Oma und zwei Onkels leben dort.

**Comment by WebCrew** [comment]
Thank you Felix for taking care of it yourself. That's very kind of you. I only have the simplest know-how when it comes to GitHub and I'm not a developer genius either lol. By the time you would have explained all this to me old sack or I had acquired the level of knowledge, Easter and Christmas would probably have fallen on the same day. Thanks.

Do I have to do anything else now?

Kind regards, Andreas 

Update: Ja die Welt ist manchmal echt klein - ist ja echt witzig :)

**Pull request merged**
